version: "3"

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: db
    env_file: .env  
    restart: always
    volumes:
      - dbdata:/var/lib/mysql 
    command: --disable-partition-engine-check   

  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - '8081:80'
    env_file: .env  

  # Wordpress
  wordpress:  
    container_name: wordpress
    depends_on:
      - db
    build: .
    env_file: .env 
    volumes:
      - wordpress:/var/www/html

  nodejs:
    container_name: nodejs    
    build: 
      context: .
      dockerfile: nodejs_microservice/Dockerfile
    depends_on:
      - db
    env_file: .env  
    command: "node server.js" 
    volumes:
      - tg_data:/usr/src/app/th_chats.txt

  # Веб-сервер
  nginx:
    container_name: nginx
    image: nginx:alpine 
    ports:
      - "8100:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro   

  # Wordpress CLI
  wp-cli:
    container_name: wp-cli
    depends_on:
      - db
      - wordpress
      - nginx
    links:
      - db
      - wordpress  
    image: wordpress:cli
    user: xfs
    working_dir: /var/www/html
    command:
      /bin/sh -c 'sleep 10; wp core install --path="/var/www/html" --url="http://localhost:8100" --title="Сайт Студии Никиты Глазкова" --admin_user=admin --admin_password=admin --admin_email=foo@bar.com; wp theme list; wp theme activate ngwebstudio; wp language core install ru_RU; wp site switch-language ru_RU'
    volumes:
      - wordpress:/var/www/html                   

volumes:
  wordpress:
  tg_data:
  dbdata: {}