
version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    build: .
    tty: true
    ports:
      - '8000:80'
    restart: always
    volumes: 
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/themes/ngwebstudio
    networks:
      - app-network      

  wordpress-cli:
    depends_on:
      - wordpress
    image: wordpress:cli
    ports:
      - '8100:80'
    command: /bin/sh -c 'sleep 10; wp db reset --yes; wp core install --path="/var/www/html" --url="http://localhost:8000" --title="Local Wordpress By NGLAZKOV!" --admin_user=admin --admin_password=admin --admin_email=foo@bar.com; wp theme list; wp theme activate ngwebstudio; wp plugin install cyr2lat --activate'
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/themes/ngwebstudio
    networks:
      - app-network  
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - ./deploy/nginx-conf:/etc/nginx/conf.d
      - wordpress:/var/www/html
    ports:
      - 80:80
    links:
      - wordpress 
    command: ['nginx', '-g', 'daemon off;']   
    networks:
      - app-network    

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge    