version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress  
    volumes:
      - dbdata:/var/lib/mysql
    command: --disable-partition-engine-check  
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db:3306
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    build: . 
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress   
    volumes:
      - wordpress:/var/www/html  
      - ./:/var/www/html/wp-content/themes/ngwebstudio
    networks:
      - app-network   
    
  wp-cli:
    depends_on:
      - wordpress
    # build: 
    #   context: .
    #   dockerfile: ./Dockerfile.wp-cli
    image: wordpress:cli
    user: xfs
    tty: true
    working_dir: /var/www/html
    links:
      - db:db
    command:
      /bin/sh -c 'sleep 10;  wp core install --path="/var/www/html"--url="http://localhost:8000" --title="Local Wordpress By Docker" --admin_user=admin--admin_password=admin --admin_email=foo@bar.com; wp theme list'
    volumes:
      - wordpress:/var/www/html                
    networks:
      - app-network

  # Веб-сервер
  nginx:
    image: nginx:alpine
    ports:
      - "8100:80"
    depends_on:
      - wordpress
    volumes:
      # - ./backend/media/:/media/
      # - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro   

volumes:
  wordpress:
  dbdata: {}

networks:
  app-network:
    driver: bridge