
version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: 
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/themes/ngwebstudio
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
    networks:
      - app-network

  wordpress-cli:
    depends_on:
      - theme_bundle
    image: wordpress:cli
    command: /bin/sh -c 'sleep 10; wp db reset --yes; wp core install --path="/var/www/html" --url="http://localhost:8000" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=admin --admin_email=foo@bar.com; wp theme list; wp theme install ngwebstudio --activate'
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/themes/ngwebstudio
    networks:
      - app-network  
  
  theme_bundle:
    image: node:stable
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/www/html/wp-content/themes/ngwebstudio
    command: bash -c "cd /var/www/html/wp-content/themes/ngwebstudio && npm install && npm i -g webpack webpack-cli && npm run build && npm run bundle && npm cache clean --force"  
    depends_on:
      - wordpress  
    networks:
      - app-network    

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge    