version: "3"

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: db
    # env_file: .env  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - dbdata:/var/lib/mysql 
    command: --disable-partition-engine-check   

  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    links: 
      - db
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db:3306  
  #   env_file: .env  

  # Wordpress
  wordpress:  
    container_name: wordpress
    depends_on:
      - db
    build: .
    # env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress    
    volumes:
      - wordpress:/var/www/html

  nodejs:
    container_name: nodejs    
    build: 
      context: .
      dockerfile: nodejs_microservice/Dockerfile
    depends_on:
      - db
    # env_file: .env  
    command: "node server.js" 

  # Веб-сервер
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8100:80"
    depends_on:
      - wordpress
      - nodejs
    volumes:
      - wordpress:/var/www/html
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro   

  # Wordpress CLI
  wp-cli:
    tty: true
    stdin_open: true
    container_name: wp-cli
    depends_on:
      - db
      - wordpress
      - nginx
    links:
      - db
      - wordpress  
    image: wordpress:cli
    user: xfs
    working_dir: /var/www/html
    command:
      /bin/sh -c 'sleep 10; wp core install --path="/var/www/html" --url="http://localhost:8100" --title="Сайт Студии Никиты Глазкова" --admin_user=admin --admin_password=admin --admin_email=foo@bar.com; wp theme list; wp theme activate ngwebstudio; wp language core install ru_RU; wp site switch-language ru_RU'
    volumes:
      - wordpress:/var/www/html                   

volumes:
  wordpress:
  dbdata: {}