FROM wordpress:cli
WORKDIR /
RUN echo "HELLO!"
CMD /bin/sh -c 'sleep 20; wp db reset --yes; wp core install --path="/var/www/html"--url="http://localhost:8000" --title="Local Wordpress By Docker" --admin_user=admin--admin_password=admin --admin_email=foo@bar.com; wp theme list'